config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'contacts#index'
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :contact_attributes, inverse_of: :contact, dependent: :destroy
  accepts_nested_attributes_for :contact_attributes, allow_destroy: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :first_name, :address, presence: true

  paginates_per 20
end

app/models/contact_attribute.rb
class ContactAttribute < ApplicationRecord
  belongs_to :contact, inverse_of: :contact_attributes
  validates :name, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_contact, only: [:edit, :show, :update, :destroy]

  def index
    @contacts = current_user.contacts.page params[:page]
  end

  def show
  end

  def edit
  end

  def new
    @contact = Contact.new
    @contact.contact_attributes.build
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    if @contact.save
      flash[:success] = "Contact succesfully created"
      redirect_to contacts_path
    else
      @contact.contact_attributes.build unless @contact.contact_attributes.present?
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      flash[:success] = "Contact succesfully updated"
      redirect_to contacts_path
    else
      @contact.contact_attributes.build unless @contact.contact_attributes.present?
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

  private
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :address,
      :fixed_phone, :mobile_phone, :image,
      contact_attributes_attributes: [:id, :name, :content, :_destroy])
    end

    def get_contact
      @contact = current_user.contacts.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController  < Devise::RegistrationsController
  # We overwrite the default Devise method to send a welcome e-mail
  def create
    super
    UserMailer.welcome_email(@user).deliver if @user.persisted?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class(flash)
    class_map = {
     "success" => "alert-success",
     "error" => "alert-danger",
     "alert" => "alert-warning",
     "notice" => "alert-info",
    }
    class_map[flash]
  end
end

app/views/contacts/_contact.slim
tr
  td = contact.first_name
  td = contact.last_name
  td = contact.address
  td = contact.mobile_phone
  td = contact.fixed_phone
  td = link_to 'Show', contact_path(contact)
  td = link_to 'Edit', edit_contact_path(contact)
  td = link_to 'Delete', contact_path(contact), method: :delete,
                         data: { confirm: 'Are you sure you want to delete this contact?' }

app/views/contacts/_contact_attribute_fields.slim
.nested-fields.row
  .col-md-4
    = f.input :name
  .col-md-4
    = f.input :content
  .col-md-4
    = link_to_remove_association "Remove Attribute", f, class: 'btn btn-default inline-button'

app/views/contacts/_form.slim
= simple_form_for @contact do |f|
  .row
    .col-sm-6
      = f.input :first_name
    .col-sm-6
      = f.input :last_name
  .row
    .col-sm-6
      = f.input :address
    .col-sm-6
      = f.input :fixed_phone
  .row
    .col-sm-6
      = f.input :mobile_phone
    .col-sm-12
      = f.input :image, as: :file
  h3 Custom Attributes
  hr
  = f.simple_fields_for :contact_attributes do |contact_attribute|
    = render 'contact_attribute_fields', f: contact_attribute if contact_attribute.object.changed? || contact_attribute.object.persisted?
  .row
    .col-sm-12
      .links
        = link_to_add_association 'Add Attribute', f, :contact_attributes, class: 'btn btn-default top-spacer'
  hr
  = f.button :submit, class: 'btn btn-primary'
  = link_to 'Back', contacts_path, class: 'pull-right'

app/views/contacts/edit.slim
h1 Edit Contact
= render 'form'

app/views/contacts/index.html.slim
table.table.table-striped
  thead
    tr
      th First Name
      th Last Name
      th Address
      th Mobile Phone
      th Fixed Phone
      th
      th
      th
  tbody
    = render @contacts

= link_to "New", new_contact_path

app/views/contacts/index.slim
h1 Contacts
hr
.table-responsive
  table.table.table-striped
    thead
      tr
        th First Name
        th Last Name
        th Address
        th Mobile Phone
        th Fixed Phone
        th Actions
        th
        th
    tbody
      = render @contacts

= link_to "New Contact", new_contact_path, class: 'btn btn-primary'
br
.text-center
  = paginate @contacts

app/views/contacts/new.slim
h1 Create Contact
= render 'form'

app/views/contacts/show.slim
.row
  .col-md-12
    = image_tag @contact.image.url, class: 'img-responsive img-space'
.row
  .col-md-12
    .table-responsive
      table.table.table-striped
        tbody
          tr
            td First Name:
            td = @contact.first_name
          tr
            td Last Name:
            td = @contact.last_name
          tr
            td Address:
            td = @contact.address
          tr
            td Mobile Phone:
            td = @contact.mobile_phone
          tr
            td Fixed Phone:
            td = @contact.fixed_phone
          - @contact.contact_attributes.each do |contact_attribute|
            tr
              td = contact_attribute.name
              td = contact_attribute.content
.row
  .col-md-12
    = link_to 'Back', contacts_path, class: 'pull-right'

app/views/layouts/application.slim
doctype html
html
  head
    title AddressBook
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/navigation' if user_signed_in?
    = render 'shared/flash'
    .container
      = yield

app/views/shared/_flash.slim
- flash.each do |type, message|
  div class="alert #{bootstrap_class(type)} fade in"
    = message

app/views/shared/_navigation.slim
nav.navbar-default
  .container-fluid
  .collapse.navbar-collapse
    ul.nav.navbar-nav
      li
        = link_to "Contacts", contacts_path
    ul.nav.navbar-nav.navbar-right
      li
        = link_to "Sign out", destroy_user_session_path, method: :delete